### ISSUE TITLE
Error 500 and field not displaying

### ISSUE THREAD

**Issue by niladam** [kpolicar/nova-date-range#2]
Hello,

I'm getting an error 500 when attempting to use the package.

Apparently, it's searching for `/nova-api/styles/date-range` which causes an error 500.

This appears to be related to the fact that you do not have a dist folder.

Basically the error is:

```
file_get_contents(***REDACTED***/vendor/kpolicar/nova-date-range/src/../dist/css/field.css): failed to open stream: No such file or directory
```

**LATER EDIT**: Other than that -- thank you for your work and for this package. I think this should be in core to be honest :)

**Comment by niladam** [comment]
It appears that your .gitignore ignores the /dist folder -- so i'm guessing why this issue arrises.

You'll need to remove that and add the folder (in case it's not added) and commit again :)

**Comment by kpolicar** [comment]
Ah yes, I'm still quite new to this, my thoughts were that it should be ignored. Thanks for the heads up and PR 👍 
Cheers

**Comment by niladam** [comment]
@kpolicar -- no worries. Errors happen. You're welcome :)
