### ISSUE TITLE
Unable to set a Label different from column name

### ISSUE THREAD

**Issue by vineeth030** [kpolicar/nova-date-range#4]
Hi, 

My from & to table columns are "dates_to_avoid_start" & "dates_to_avoid_end". I need to setup label "Dates to avoid" for date range. How can I setup such a label? Is it possible?

**Comment by vineeth030** [comment]
Figured out myself.

`DateRange::make(['dates_to_avoid_start' => 'From', 'dates_to_avoid_end' => 'To'])`

Very useful and easy to setup Nova package.Thanks!

**Comment by vineeth030** [comment]
It didnt work. When i tried above code, Nova updated my label but now it tries to insert to field names "from" and "to". But as I mentioned before my fields are 'dates_to_avoid_start' and 'dates_to_avoid_end'.

**Comment by kpolicar** [comment]
Hello @vineeth030 ,
Try this:
`DateRange::make('Dates to avoid', ['dates_to_avoid_start', 'dates_to_avoid_end'])`
